<?php

namespace AppBundle\Repository;

/**
 * CartelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartelRepository extends \Doctrine\ORM\EntityRepository
{
}
