<?php

namespace AppBundle\Repository;

/**
 * DailyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyRepository extends \Doctrine\ORM\EntityRepository
{
}
