<?php

namespace AppBundle\Repository;

/**
 * PreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreguntaRepository extends \Doctrine\ORM\EntityRepository
{
 public function getRandom(){
     $query = $this->_em->createQuery("Select AppBundle:Pregunta p Orderby rand()");
     $result = $query->setMaxResults(1)->execute();
     return $result;
 }
}
