<?php

namespace AppBundle\Repository;

/**
 * SuscripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuscripcionRepository extends \Doctrine\ORM\EntityRepository
{
}
